
variables:
- name: big_var_01
  value: ${{ parameters.big_var_01 }}



parameters:
  - name: big_var_01
    displayName: "this var wants to get written to then read by templates"
    type: string
    default: "3q4w#V$X3q4w#V$X"
  - name: image
    displayName: Pool Image
    type: string
    default: ubuntu-latest
    values:
    - windows-latest
    - vs2017-win2016
    - ubuntu-latest
    - ubuntu-16.04
    - macOS-latest
    - macOS-10.14


# CI Triggers
trigger:
  branches:
    exclude:
      - '*'

pool: 
  vmImage: ${{ parameters.image }}


# Release Stages
stages:

- template: child_scott_one.yaml

- template: child_scott_two.yaml

